<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * This table stores synced clinical reports from CouchDB.
     * Reports are generated by the AI system and include discharge summaries,
     * clinical handovers, referral reports, and comprehensive reports.
     */
    public function up(): void
    {
        Schema::create('stored_reports', function (Blueprint $table) {
            $table->id();
            $table->string('report_uuid', 36)->unique();
            
            // Document identification
            $table->string('couch_id')->unique()->comment('CouchDB document ID');
            $table->string('report_type', 50)->comment('discharge, handover, referral, comprehensive');
            
            // Session and patient linkage
            $table->string('session_couch_id')->nullable()->index();
            $table->string('patient_cpt')->nullable()->index();
            
            // Report metadata
            $table->string('filename')->nullable();
            $table->string('mime_type', 100)->default('application/pdf');
            $table->unsignedBigInteger('size_bytes')->default(0);
            
            // Content storage
            // PDF content stored as base64 or path to file
            $table->longText('pdf_base64')->nullable()->comment('Base64 encoded PDF content');
            $table->text('pdf_path')->nullable()->comment('Path to stored PDF file if using filesystem');
            $table->longText('html_content')->nullable()->comment('HTML version of the report');
            
            // Generation metadata
            $table->timestamp('generated_at')->nullable();
            $table->unsignedBigInteger('generated_by_user_id')->nullable();
            $table->string('generated_by_name')->nullable();
            
            // Sync tracking
            $table->boolean('synced')->default(true)->comment('Whether synced from CouchDB');
            $table->timestamp('synced_at')->nullable();
            $table->timestamp('couch_updated_at')->nullable()->comment('Last update in CouchDB');
            
            // Raw document for audit
            $table->json('raw_document')->nullable()->comment('Full CouchDB document');
            
            $table->timestamps();
            
            // Indexes for common queries
            $table->index(['report_type', 'generated_at']);
            $table->index(['session_couch_id', 'report_type']);
            $table->index('synced_at');
            
            // Foreign key to users table
            $table->foreign('generated_by_user_id')
                ->references('id')
                ->on('users')
                ->onDelete('set null');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('stored_reports');
    }
};
